#include "seventeencard.h"
SeventeenCard::SeventeenCard()
    : seen_count(0)
    , avg_seen(0.0)
    , pick_count(0)
    , avg_pick(0.0)
    , game_count(0)
    , win_rate(0.0)
    , opening_hand_game_count(0)
    , opening_hand_win_rate(0.0)
    , drawn_game_count(0)
    , drawn_win_rate(0.0)
    , ever_drawn_game_count(0)
    , ever_drawn_win_rate(0.0)
    , never_drawn_game_count(0)
    , never_drawn_win_rate(0.0)
    , drawn_improvement_win_rate(0.0)
{}
